### ISSUE TITLE
Problems with ChaCha

### ISSUE THREAD

**Issue by janicetr** [philanc/luazen#12]
Hello!

The following code returns an assertation error after xchacha_decrypt:

> if lz.xchacha_encrypt then
	print("testing xchacha...")
	local k = string.rep("k", 32)
	local n = string.rep("n", 24)
	local a = string.rep("a", 10)
	local m = string.rep("m", 20)
	-- test defaults
	local c1 = lz.xchacha_encrypt(k, n, m)
	assert(#c1 == 0 + #m + 16)
	local p1, a1 = lz.xchacha_decrypt(k, n, c1)
	assert(p1 ~= nil and p1 == m and a1 == "")
	-- test with aad
	local c2 = lz.xchacha_encrypt(k, n, m, 0, a)
	assert(#c2 == #a + #m + 16)
	local p2, a2 = lz.xchacha_decrypt(k, n, c, 0, #a)
	assert(p2 ~= nil and p2 == m and a2 == a)
end

Win10 x64, lua 5.3.5, gcc 8.1 (mingw)

Can you help me out here? 

Thanks in advance!

**Comment by philanc** [comment]
Hi janicetr,

Did you install luazen with luarocks, or did you use the makefile?

What is your luazen version?

`  lz = require "luazen"; print(lz.VERSION)`

**Comment by philanc** [comment]
Thanks for the report. I fixed a bug in xchacha_decrypt() and added a test in test/test_luazen.lua.

In the test you posted above, the line
`local p2, a2 = lz.xchacha_decrypt(k, n, c, 0, #a)`
should be changed to 
`local p2, a2 = lz.xchacha_decrypt(k, n, c2, 0, #a)`
(c => c2), and it should run ok with version 0.15 (last version / master)

**Comment by janicetr** [comment]
Thank you! I've tested it with huge strings (50Mb+) and it worked fast and precise. Best regards: J.
