### ISSUE TITLE
Output od luazen.lzma cannot be decompressed by lzma command line utility (linux)

### ISSUE THREAD

**Issue by StanleyP** [philanc/luazen#13]
It returns lzma: (stdin): File format not recognized.
Any chance to make output compatible with other lzma tools?

**Comment by philanc** [comment]
Hi StanleyP,

My initial plan was to include only an efficient and compact (as in _small binary size_) compression function in luazen.  So I wrapped the compress/decompress functions implementing the LZMA compression _algorithm_.  I didn't pay attention to the _file format_ used by standard lzma tools.

I will have a look at the LZMA standard file format and see if I can/want to support it.  Coming back to you here ASAP.

**Comment by philanc** [comment]
So I looked at the lzma standard format. It is simple, and not much different from the luazen one. (and I should have adopted it in the first place...).  But now, there may be users with data compressed with the luazen format so I cannot just change the format without notice.

To help with your issue, I have added a lua module ('lzma_std_fmt.lua') with a function to convert compressed strings from the luazen format to the standard format (as used by the linux lzma command). It also include replacement for the lzma() and unlzma() functions in luazen.

Let me know if it works for you.

I will deprecate the luazen format and in the long term, I will completely replace it with the standard lzma format. At the moment I have not figured out the transition details.

Phil

**Comment by StanleyP** [comment]
You are the best! I tested it and it works now!
Thank you for such a quick fix and will be looking for fix in luazen as well.
Take care.

**Comment by philanc** [comment]
Just to let you know: the last commit f0cd334790f73b969c8277bb1953ee85cdb8c082 (version 0.16) modifies the lzma and unlzma functions. 

lzma() now compresses to the standard lzma format

unlzma() now transparently uncompresses strings compressed either in the new standard lzma format or in the former "legacy" luazen format. 

So with this version, the Lua conversion function is not needed anymore.

Phil

**Comment by StanleyP** [comment]
Perfect! Gonna test/try it right away. Thanks again!
