### ISSUE TITLE
Some corrections proposed

### ISSUE THREAD

**Issue by shmuz** [philanc/luazen#14]
I compiled this library for Windows with MinGW (GCC 8.1.0) - total 8 compilations (Lua 5.1-5.4, x86 and x64).
There were 3 issues with it (a [diff](https://github.com/philanc/luazen/files/5813941/diff.txt) file attached).
The issues were as follows:

1. lzf.c did not compile for x64 architecture (GCC wants __int64 rather than _int64)
2. luazen.unlzma did not work properly (because on Windows long int is always 32 bit wide)
3. The test failed with standard Lua 5.1 because Lua 5.1 didn't accept hex escape sequences in strings.

Thank you for this excellent library!

**Comment by shmuz** [comment]
I forgot to mention that those diffs are relative to version 0.16.
Now that I checked the 2 commits after it I saw that the issue with lzma was already fixed.

**Comment by philanc** [comment]
Hi Shmuel, 

Thanks for your lzf.c and test_luazen.lua fixes.  They are included in master.

I don't have any Windows platform available anymore.  So I cannot test luazen on Windows. Last time I built it on Windows was quite a long time ago with VC which supports `_int64` (or supported it at the time). I think/hope it also supports `__int64`!

Regarding hex escape sequences in strings (`"\x01"`), I support Lua 5.3+  (but I am happy that it works with older versions!).

Thanks again for the fixes and the Windows / Lua 5.1 test.

Phil

**Comment by shmuz** [comment]
Hi Phil,

I'm happy that you made use of my proposals.
Yes, the library works with all versions Lua 5.1-5.4 and also LuaJIT 2.1 (all the tests from test_luazen.lua pass).
Thank you again.
