### ISSUE TITLE
Does not compile under Windows

### ISSUE THREAD

**Issue by oktoberfest6** [philanc/luazen#16]
Hi,

I try to install your module under Windows (using Visual Studio 2019) and it fails... but I found why :)
- "win32" is not listed in the supported platforms
- the "advapi32" library is needed on link

I'm not an expert in rockspec files but I got it working with following changes :

`supported_platforms = {  "unix", "win32", }`

and I added this line in the modules table (I don't known if there is a prettier way to display code in an issue)
`platforms = { win32  = { modules = { luazen = { libraries = { "advapi32" } } } } },`

**Comment by philanc** [comment]
Thanks for the issue. Unfortunately, I have no longer access to a Windows platform and so, I cannot test anymore the build and the code on windows. This is why the rockspec does only mention "unix" as a supported platform

I am glad you found a fix that works in your environment, but I cannot even test it!  :-(  Sorry.

**Comment by danielherrero** [comment]
Hi
Thanks to @oktoberfest6 I could try to compile but I get this error. Just in case someone could solve it
![image](https://github.com/user-attachments/assets/0acafc43-a681-44e1-bb4f-11c980886695)
