### ISSUE TITLE
ed25519 verify false

### ISSUE THREAD

**Issue by Jon-Gaara** [philanc/luazen#17]
hello，philanc:
   I recently used your project for ed25519 signature verification, but I found that I always failed to pass the signature verification
`
local lz = require "luazen"
function _M.check_ed25519()
    local message = "GET/gateway/token"
    local sig = hextos("de2f2169f245a6168eea920c69f4693496caafff7ee842a3fe60a61acd614d7815591abefb9c5b6663c9bb41a4a17dd3982b4feea885106f5ddde8b41507410f")
    local pk = hextos("74ba5bf8fc59781c9428e7c0ced103233fb24c4ad267ad50b1f4bf8cbd9163bd")
    return lz.check(sig, pk, message)
end
`

luazen version: 0.9-1
lua  version: 5.1.5

**Comment by philanc** [comment]
Hi Jon-Gaara,

Could you use a more recent version? ideally the last version 0.16.   The API is now more stable and aligned with the original NaCl API by the original author Dan Bernstein.

The current API uses "attached signatures", that is, the signature is now included in the signed message (it is actually inserted at the beginning of the message):

```
x25519_sign(sk, pk, text) => signed text
	sign a text with a secret key
	sk is the secret key as a 32-byte string
	pk is the public key as a 32-byte string
	text is the text to sign as a string
	Return the signed text which contains  a 64-byte signature
	followed by the original text.

x25519_sign_open(stext, pk) => text
	check a text signature with a public key
	stext is the signed text to verify
	pk is the public key as a 32-byte string
	if the signature is valid, return the original text, or (nil, errmsg)
```

Using your example:
```
local lz = require "luazen" 
local message = "GET/gateway/token"
local sig = hextos( "de2f2169f245a6168eea920c69f4693496caafff7ee842a3fe60a61acd614d7815591abefb9c5b6663c9bb41a4a17dd3982b4feea885106f5ddde8b41507410f") 
local pk = hextos("74ba5bf8fc59781c9428e7c0ced103233fb24c4ad267ad50b1f4bf8cbd9163bd") 

local signed_message = sig .. message
print( lz.x25519_sign_open(signed_message, pk) )
-- this prints the original message: "GET/gateway/token"  so the signature is good.
-- if the signature was invalid, this would print nil, error message

(note: I tested this with luazen-0.16 and lua 5.4)

**Comment by Jon-Gaara** [comment]
No,I cannot, I use Apisix which only supports Lua 5.1

**Comment by philanc** [comment]
I just rebuilt luazen.so  (from the latest luazen-0.16) with lua-5.1.5 and the code above works.  The signature 'sig' can be verified.

Can you build the latest luazen from source?

**Comment by Jon-Gaara** [comment]
yes，I can
