### ISSUE TITLE
missing underscore in win64 build exception for lzf

### ISSUE THREAD

**Issue by jaromil** [philanc/luazen#4]
Many thanks for luazen! I found a small issue and can also make a PR if you like.

Please note the type declaration here:
https://github.com/philanc/luazen/blob/cb849cb99f2f5cedf17062fb0e6f7f7ea1223dc0/src/lzf_c.c#L123
should use __int64 instead, which seems to be the correct type name in winzoz. I am testing using mingw32 in cross compilation for target w64.

**Comment by philanc** [comment]
It looks like _int64 should be defined as a synonym to __int64.
See https://technet.microsoft.com/en-us/subscriptions/befeaky0%28v=vs.100%29.aspx
~at the end of the page: "For backward compatibility, single-underscore versions of the rest of the keywords are supported."

So I guess either they removed this compatibility, or it is not defined in your environment.
I did build it recently with Visual Studio VC 14, but don't have it handy now. Will look into it when I can.

Thanks for the report

**Comment by jaromil** [comment]
[OT] BTW would you be interested in including classic boring ECDH and RSA in luazen? I'd pack a PR here then. I'm porting a C implementation already to LUA and could simply add it to your collection if you like. I'm using luazen here https://github.com/DECODEproject/zenroom patched and with some namespace changes I'm not bothering you with.

**Comment by philanc** [comment]
Hi Denis,  zenroom looks like an interesting project. Will read about the overall DECODE project.

re. ECDH and RSA, I will not include them in luazen since I want to keep the size as tiny as possible for some projects here.  I even consider removing md5 and rc4, and have them in a separate "legacy" lib (maybe along with SHA-1 and SHA-256). 

And I may also remove LZF (or move it to the legacy lib) and keep only BriefLZ for compression.

OTOH, if you have a compact ECDH + RSA (+ maybe AES?) Lua lib, I might be interested in using it as-is.  For my use cases, the priority is not raw performance, but small code size.

Let me know if you bundle these as a Lua lib!  Thanks.

**Comment by jaromil** [comment]
dear Phil, I agree overall with your decisions, myself very much of a fan of minimalism. FWIW I agree also RC4 and MD5 can stay out of luazen. After some testing I'm also determined to limit choice in Zenroom, but for that I need first to listen to needs of colleagues. Understood about the library. I'm just not sure I can curate it well as you do in luazen, since I have less experience with LUA and mostly statically including stuff in Zenroom, but I'll let you know when the implementation is ready. I'm aiming at ECDH + RSA and SHA256/512 and SHA3 and of course NIST AES.

**Comment by philanc** [comment]
Hi Denis,  Very good!  This could be my "classic-modern" crypto lib!

FYI, I also have two other projects that may interest you:

plc - https://github.com/philanc/plc - these are "modern" crypto algorithms written in pure Lua (Lua 5.3 only). I tried to make them as fast as possible (eg. 4 sec to encrypt 10MB with NORX) , but of course this is pure, interpreted Lua...  Anyway, maybe useful for small volumes and/or where standard or embedded Lua is used and compiled code cannot be added.

slua - https://github.com/philanc/slua - this is Lua 5.3, statically compiled with musl libc and a few tiny libs, including luazen. This is my "Lua swiss army knife!  I include pre-built binaries for Linux x86_64, i586 and armhf (v7).  This is linux only.

**Comment by jaromil** [comment]
Oh! slua now is very interesting. I am gutting lua_sandbox and noticing a lot of things I don't like in it, first and foremost the dynamic memory allocation, so in the back of my mind I do have a mid-long term plan to ditch it for something else, but this very much depends from the zenroom adoption in DECODE project and beyond. So far so good, I'll add slua on my map.

**Comment by jaromil** [comment]
Our projects have so many things in common! we may want to have a face2face meeting and evaluate to join forces, even. I also use linenoise from Antirez :^) who is also a friend. The only difference in zenroom is that I want to deny any access to i/o (filesystem) or os operations. the TCP connection capability is interesting and could work well with socks4 or 5 since all connections we do in DECODE are over Tor.

**Comment by philanc** [comment]
Hi Denis, I just browsed around the dyne.org and DECODE projects. It looks like you all have a lot of fun and interesting stuff there! I definitely must have a deeper look!!

(Re Antirez:  I don't know him, but I am a big admirer of his work (Redis, linenoise), and I like his style!)

**Comment by jaromil** [comment]
[OT] Heard of the new CAESAR results? any new plans? would love to continue our conversation via email, if you like please write me at jaromil@dyne.org
