### ISSUE TITLE
luarocks update needed?

### ISSUE THREAD

**Issue by SWSAmor** [philanc/luazen#5]
Hi! Thank you for your great work, especially for the Curve25519 implementation. 👍 

I think something happened with the last version:
```
luarocks install luazen
Installing https://rocks.moonscript.org/luazen-0.9-1.rockspec...
Using https://rocks.moonscript.org/luazen-0.9-1.rockspec... switching to 'build' mode
Cloning into 'luazen'...
remote: Counting objects: 29, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 29 (delta 3), reused 12 (delta 1), pack-reused 0
Receiving objects: 100% (29/29), 68.48 KiB | 511.00 KiB/s, done.
Resolving deltas: 100% (3/3), done.
gcc -O2 -fPIC -I/usr/include -c src/luazen.c -o src/luazen.o
gcc -O2 -fPIC -I/usr/include -c src/base58.c -o src/base58.o
gcc -O2 -fPIC -I/usr/include -c src/lzf_c.c -o src/lzf_c.o
gcc: error: src/lzf_c.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
distcc[13270] ERROR: compile src/lzf_c.c on localhost failed

Error: Build error: Failed compiling object src/lzf_c.o
```

**Comment by philanc** [comment]
Thanks for the report.  The rockspec for the last stable version luazen-0.9-1.rockspec was buggy (missing the github branch v0.9).  Hopefully it should work now. I close the issue, but please reopen if it doesn't work for you.

**Comment by SWSAmor** [comment]
It is compiled successfully, thank you. I saw you renamed some function, so i did it too. But now i get:
> attempt to call field 'x25519_sign' (a nil value)

Maybe i compiled an older version? I didn't find where luarocks download c source, but found the test_luazen.lua and it's different (it seems older) than the github one. What's happening?
Here's the luarocks log, hope it helps:

luarocks install luazen
Installing https://rocks.moonscript.org/luazen-0.9-1.rockspec...
Using https://rocks.moonscript.org/luazen-0.9-1.rockspec... switching to 'build' mode
Cloning into 'luazen'...
remote: Counting objects: 33, done.
remote: Compressing objects: 100% (30/30), done.
Receiving objects: 100% (33/33), 60.67 KiB | 460.00 KiB/s, done.
Resolving deltas: 100% (2/2), done.
remote: Total 33 (delta 2), reused 21 (delta 2), pack-reused 0
Note: checking out 'cb849cb99f2f5cedf17062fb0e6f7f7ea1223dc0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

gcc -O2 -fPIC -I/usr/include -c src/luazen.c -o src/luazen.o
gcc -O2 -fPIC -I/usr/include -c src/base58.c -o src/base58.o
gcc -O2 -fPIC -I/usr/include -c src/lzf_c.c -o src/lzf_c.o
gcc -O2 -fPIC -I/usr/include -c src/lzf_d.c -o src/lzf_d.o
gcc -O2 -fPIC -I/usr/include -c src/mono.c -o src/mono.o
gcc -O2 -fPIC -I/usr/include -c src/norx.c -o src/norx.o
gcc -O2 -fPIC -I/usr/include -c src/md5.c -o src/md5.o
gcc -O2 -fPIC -I/usr/include -c src/rc4.c -o src/rc4.o
gcc -O2 -fPIC -I/usr/include -c src/brieflz.c -o src/brieflz.o
gcc -O2 -fPIC -I/usr/include -c src/depacks.c -o src/depacks.o
gcc -O2 -fPIC -I/usr/include -c src/randombytes.c -o src/randombytes.o
gcc -shared -o luazen.so -L/usr/lib64 src/luazen.o src/base58.o src/lzf_c.o src/lzf_d.o src/mono.o src/norx.o src/md5.o src/rc4.o src/brieflz.o src/depacks.o src/randombytes.o
Updating manifest for /usr/lib64/lua/luarocks/lib/luarocks/rocks
luazen 0.9-1 is now built and installed in /usr/lib64/lua/luarocks (license: MIT)

**Comment by SWSAmor** [comment]
Oh it's just sign not x25519_sign.
