### ISSUE TITLE
argon2i verify how

### ISSUE THREAD

**Issue by SWSAmor** [philanc/luazen#6]
I want to use argon2i but I don't understand how could i verify a encrypted password? I saw another implementation and there was a function for that. 
Sry, maybe I'm a little uninformed in cryptography.

**Comment by philanc** [comment]
The argon2i function doesn't verify a password. It just compute a value (32-byte binary string) from a password. With the same parameters, it should always return the same value for a given password.

This can be used for password hashing [1] or to generate encryption keys, and make brute force attacks more expensive.

[1] https://en.wikipedia.org/wiki/Cryptographic_hash_function#Password_verification

**Comment by SWSAmor** [comment]
I thought the same, but i saw here https://github.com/thibaultcha/lua-argon2/blob/master/src/argon2.c this:
`ret_code = argon2_verify(encoded, plain, plainlen, variant);`
and didn't understand why is that?

What do you mean about same parameters `salt, nkb, niter` all three matters?

**Comment by philanc** [comment]
(1) yes all parameters matter. If you change any one of them, the value computed for a password will change.

(2) you can implement a verify function yourself in Lua:
```
variant = { salt = "ANYTHING", nkb = 20000, niter=10 } -- use 20 MB, 10 iterations

function verify(hashedpassword, password, variant)
    local h = luazen.argon2i(password, variant.salt, variant.nkb, variant.iter)
    return (h == hashedpassword)
end

function hash(password, variant)
    return luazen.argon2i(password, variant.salt, variant.nkb, variant.iter)
end
-- Now for example when a user defines a password, 
-- you store the hash of the password:
hashed_password = hash(password, variant); 
-- and when the user enters the password, you can verify it with:
if verify(hashed_password, password, variant) then
    print("Ok, the password is good")
    ... do something
else 
    print("Bad password!!!")
end
```
Hope it makes things clearer.

**Comment by SWSAmor** [comment]
Yes, understand. Thank you for the example. :-)
