### ISSUE TITLE
Renames in README.md

### ISSUE THREAD

**Issue by SWSAmor** [philanc/luazen#7]
Would you rename/replace these:
>x25519_sign_public_key -> sign_public_key
x25519_sign -> sign
x25519_sign_open -> check
ec25519_public_key -> x25519_public_key
ed25519_public_key -> sign_public_key

**Comment by philanc** [comment]
I think you may be mixing the last stable version (v0.9) and the current version (master, which is to become v0.10, moving slowly towards a v1.0).  I have made heavy changes between v0.9 and v0.10, both implementation and API. I want to have a good and hopefully stable API before tagging the v1.0.

As indicated at the top of the README file, the last stable version is v0.9 at https://github.com/philanc/luazen/releases/tag/v0.9.  Get the zip file at tghis link to download a complete v0.9 tree, including test_luazen.lua and README.  The most recent rockspec is also for v0.9.  

Alternatively on github, at the project home page, you may click the "Branch master" button (above the files on the left) and select tag v0.9 -- or go at https://github.com/philanc/luazen/tree/v0.9 to see the v0.9 tree.

So, to test the v0.9 version by the rockspec, use test/test_luazen.lua in the v0.9 tree.

Sorry for the confusion. I could have made it more explicit.
