### ISSUE TITLE
Error with ed signature check

### ISSUE THREAD

**Issue by SWSAmor** [philanc/luazen#8]
When i want to call check aka x25519_sign_open with the two parameters (stext, pk) i get this:
`bad argument #3 to 'check' (string expected, got no value)`

**Comment by philanc** [comment]
I think this is the same problem as issue #7 - see my answer at https://github.com/philanc/luazen/issues/7#issuecomment-383246704

Sorry for the API change. I want to make it good before v1.0. After that, API changes should occur only at major version changes. So the v1.0 API will be stable until v2.0.
