### ISSUE TITLE
Crash in assert

### ISSUE THREAD

**Issue by edubart** [philanc/luazen#9]
This is odd, this library works fine when running a script, but when I use it in combination with `busted` and many test files it crashes with:

```
lua5.3: src/luazen.c:55: llib_append: Assertion `llib_top < LT_SIZE' failed.
Aborted (core dumped)
```

The only code in my tests files is a simple `require`:
```lua
local lz = require 'luazen'
```

**Comment by edubart** [comment]
Oh I get why, `busted` sets all `package.loaded` to nil when a test unit finishes, so `luaopen_luazen` will be called again for each `require` in different test suits.

In case you don't know, `busted` is a popular unit testing for lua. https://github.com/Olivine-Labs/busted

**Comment by edubart** [comment]
In case you fix this, please upload the latest rockspec to luarocks.

**Comment by edubart** [comment]
A simple fix is this:

```diff
diff --git a/src/luazen.c b/src/luazen.c
index 5c60453..828a73d 100644
--- a/src/luazen.c
+++ b/src/luazen.c
@@ -71,6 +71,7 @@ static int llib_append(const char *fname, lua_CFunction func) {
        llib_append(#NAME, ll_ ## NAME);
 
 static void llib_init() {
+       llib_top = 0;
        // luazen function declarations - comment APPEND lines to 
        // remove functions from the luazen build
        //
```

**Comment by philanc** [comment]
Thanks for the heads up and for the diagnostic. Will fix it ASAP.

**Comment by philanc** [comment]
> Oh I get why, `busted` sets all `package.loaded` to nil when a test unit finishes, so `luaopen_luazen` will be called again for each `require` in different test suits.
> 
> In case you don't know, `busted` is a popular unit testing for lua. https://github.com/Olivine-Labs/busted

I have heard about busted, but never used it. I will look into it. Thanks.

**Comment by edubart** [comment]
Closing because you have fixed on master.
